# Generated by Django 3.0 on 2020-05-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200510_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Email_ID',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
