# Generated by Django 3.0 on 2020-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
