# Generated by Django 3.0 on 2020-05-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200512_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
