# Generated by Django 3.0 on 2020-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200510_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default='8554471063', editable=False, max_length=10, unique=True),
        ),
    ]
