# Generated by Django 3.0 on 2020-05-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200511_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default='9834891059', editable=False, max_length=10, unique=True),
        ),
    ]
