# Generated by Django 3.0 on 2020-05-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200511_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default='8151800641', editable=False, max_length=10, unique=True),
        ),
    ]
