# Generated by Django 3.0 on 2020-05-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200512_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default='8078921463', editable=False, max_length=10, unique=True),
        ),
    ]
