# Generated by Django 3.0 on 2020-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200512_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default='9110931567', editable=False, max_length=10, unique=True),
        ),
    ]
