# Generated by Django 3.0 on 2020-05-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200512_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default='9364909640', editable=False, max_length=10, unique=True),
        ),
    ]
