# Generated by Django 3.0 on 2020-05-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200512_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default='9995528357', editable=False, max_length=10, unique=True),
        ),
    ]
