# Generated by Django 3.0 on 2020-05-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200513_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default='9474465335', editable=False, max_length=10, unique=True),
        ),
    ]
