# Generated by Django 3.0 on 2020-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(blank=True, default=-1, null=True)),
                ('transaction_type', models.CharField(default='', max_length=50)),
                ('amount_transfered_to', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('Initial_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('Final_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
