# Generated by Django 3.0 on 2020-05-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passbook', '0002_auto_20200513_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passbook',
            name='transaction_type',
        ),
    ]
