# Generated by Django 3.0 on 2020-05-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbook', '0003_remove_passbook_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='passbook',
            name='transaction_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
